2025-03-27 15:50:09,898 - Cleared log file: /home/pi/smartcart/Pick-and-go-CS/src/app/logs/service.log
2025-03-27 15:50:14,906 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9066c10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:50:14,906 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:50:21,918 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a68d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:50:21,919 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:50:28,932 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90baa10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:50:28,933 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:50:35,946 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b65d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:50:35,947 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:50:42,959 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb975b090>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:50:42,959 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:50:49,971 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9083550>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:50:49,971 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:50:56,983 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9080610>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:50:56,984 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:51:03,995 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab910>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:51:03,996 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:51:11,001 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9a50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:51:11,001 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:51:18,010 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bbf10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:51:18,010 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:51:25,019 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9081110>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:51:25,020 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:51:32,029 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9080dd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:51:32,029 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:51:39,041 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9a50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:51:39,041 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:51:46,049 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b7b90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:51:46,049 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:51:53,060 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b7490>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:51:53,060 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:52:00,072 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a3ad0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:52:00,073 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:52:07,084 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bb710>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:52:07,085 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:52:14,093 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a6490>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:52:14,094 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:52:21,103 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b48d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:52:21,103 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:52:28,112 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9e10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:52:28,113 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:52:35,125 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9080310>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:52:35,125 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:52:42,133 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90819d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:52:42,134 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:52:49,141 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ba390>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:52:49,141 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:52:56,150 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908eed0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:52:56,151 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:53:03,160 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9082b50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:53:03,160 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:53:10,169 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9080050>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:53:10,169 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:53:17,173 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9c50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:53:17,173 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:53:24,182 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b6d10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:53:24,182 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:53:31,191 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9278390>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:53:31,193 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:53:38,204 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92aaa90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:53:38,205 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:53:45,213 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908fe90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:53:45,213 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:53:52,221 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b6f50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:53:52,222 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:53:59,230 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab310>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:53:59,232 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:54:06,240 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9910>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:54:06,241 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:54:13,245 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9081710>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:54:13,245 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:54:20,253 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9083d90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:54:20,253 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:54:27,257 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9066250>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:54:27,258 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:54:34,273 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908d490>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:54:34,274 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:54:41,283 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9081550>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:54:41,284 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:54:48,295 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90811d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:54:48,296 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:54:55,305 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b4f10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:54:55,305 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:55:02,318 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bb550>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:55:02,318 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:55:09,330 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bbe90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:55:09,330 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:55:16,342 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92abf50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:55:16,343 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:55:23,357 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90720d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:55:23,357 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:55:30,370 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9d10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:55:30,370 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:55:37,382 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b8210>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:55:37,382 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:55:44,395 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9e90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:55:44,395 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:55:51,408 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b5950>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:55:51,409 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:55:58,421 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90816d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:55:58,422 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:56:05,434 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9082290>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:56:05,434 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:56:12,448 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90646d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:56:12,449 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:56:19,461 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9081c50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:56:19,462 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:56:26,474 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b7ad0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:56:26,475 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:56:33,484 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b7490>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:56:33,485 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:56:40,498 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bbe50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:56:40,498 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:56:47,511 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b8e10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:56:47,512 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:56:54,524 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92abc10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:56:54,525 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:57:01,539 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9066550>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:57:01,540 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:57:08,552 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b8f50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:57:08,553 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:57:15,566 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9a90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:57:15,566 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:57:22,579 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9d50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:57:22,579 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:57:29,592 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b67d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:57:29,593 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:57:36,605 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9082f10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:57:36,605 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:57:43,614 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9065a50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:57:43,614 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:57:50,628 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90abb90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:57:50,629 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:57:57,641 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9081cd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:57:57,642 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:58:04,654 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9072c50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:58:04,655 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:58:11,667 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b7f10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:58:11,667 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:58:18,679 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bb5d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:58:18,680 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:58:25,693 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bbf90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:58:25,693 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:58:32,706 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92ab090>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:58:32,706 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:58:39,720 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aad50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:58:39,721 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:58:46,733 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9890>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:58:46,734 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:58:53,746 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ba8d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:58:53,747 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:59:00,760 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b8750>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:59:00,760 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:59:07,772 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b7a50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:59:07,773 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:59:14,781 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a97d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:59:14,782 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:59:21,797 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9083310>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:59:21,798 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:59:28,807 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a2290>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:59:28,807 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:59:35,816 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9080210>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:59:35,817 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:59:42,825 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b4a10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:59:42,826 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:59:49,838 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b78d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:59:49,839 - Status check - active: True, should_run: False, app: not running
2025-03-27 15:59:56,849 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b8a90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 15:59:56,849 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:00:03,857 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9450>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:00:03,857 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:00:10,865 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92abd50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:00:10,865 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:00:17,875 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908fa10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:00:17,875 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:00:24,884 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9067390>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:00:24,884 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:00:31,896 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bbe90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:00:31,896 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:00:38,901 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bb890>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:00:38,902 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:00:45,913 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b5510>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:00:45,913 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:00:52,921 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9072190>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:00:52,921 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:00:59,937 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9080850>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:00:59,937 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:01:06,948 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908ef90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:01:06,949 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:01:13,961 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90819d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:01:13,961 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:01:20,975 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b51d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:01:20,975 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:01:27,984 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b5c10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:01:27,984 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:01:34,996 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b8190>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:01:34,997 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:01:42,007 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b83d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:01:42,007 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:01:49,019 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a4ed0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:01:49,019 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:01:56,029 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9097850>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:01:56,029 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:02:03,037 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9067250>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:02:03,037 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:02:10,046 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ba790>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:02:10,046 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:02:17,055 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ba2d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:02:17,055 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:02:24,064 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b5610>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:02:24,064 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:02:31,072 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a3390>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:02:31,072 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:02:38,080 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9082a90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:02:38,080 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:02:45,089 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9095f50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:02:45,089 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:02:52,100 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b76d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:02:52,100 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:02:59,109 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9083090>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:02:59,110 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:03:06,122 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a0910>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:03:06,123 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:03:13,136 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9350>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:03:13,136 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:03:20,145 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9066390>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:03:20,146 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:03:27,158 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908d7d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:03:27,158 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:03:34,170 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90970d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:03:34,171 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:03:41,182 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a2e50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:03:41,183 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:03:48,191 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9b50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:03:48,191 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:03:55,200 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bab10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:03:55,201 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:04:02,210 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92abc50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:04:02,211 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:04:09,220 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b7350>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:04:09,220 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:04:16,229 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b5290>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:04:16,233 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:04:23,242 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9095f90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:04:23,242 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:04:30,251 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b7310>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:04:30,252 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:04:37,261 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908fe50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:04:37,262 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:04:44,269 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908c4d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:04:44,269 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:04:51,277 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9f90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:04:51,277 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:04:58,286 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9f10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:04:58,287 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:05:05,293 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a2350>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:05:05,293 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:05:12,305 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a3ad0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:05:12,305 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:05:19,313 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a3750>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:05:19,313 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:05:26,318 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9f10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:05:26,318 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:05:33,324 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aac10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:05:33,325 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:05:40,333 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908d650>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:05:40,333 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:05:47,343 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908da90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:05:47,343 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:05:54,356 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b5750>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:05:54,357 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:06:01,371 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90653d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:06:01,371 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:06:08,383 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b6f50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:06:08,384 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:06:15,393 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908ef10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:06:15,393 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:06:22,402 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908eb10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:06:22,403 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:06:29,412 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8650>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:06:29,413 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:06:36,423 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab010>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:06:36,423 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:06:43,436 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9066cd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:06:43,437 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:06:50,451 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9083090>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:06:50,452 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:06:57,465 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9510>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:06:57,465 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:07:04,478 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab9d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:07:04,479 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:07:11,488 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab210>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:07:11,489 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:07:18,502 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908d3d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:07:18,502 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:07:25,515 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9066f10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:07:25,516 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:07:32,528 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b7690>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:07:32,529 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:07:39,540 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9080f90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:07:39,541 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:07:46,550 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b6750>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:07:46,550 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:07:53,563 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908dc10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:07:53,563 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:08:00,572 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a6bd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:08:00,574 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:08:07,587 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab810>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:08:07,588 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:08:14,600 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8bd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:08:14,601 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:08:21,614 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a0b10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:08:21,615 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:08:28,627 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9070ad0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:08:28,628 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:08:35,641 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90678d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:08:35,642 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:08:42,654 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9010>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:08:42,655 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:08:49,668 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa3d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:08:49,669 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:08:56,682 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9659210>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:08:56,682 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:09:03,695 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908d750>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:09:03,695 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:09:10,708 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b60d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:09:10,708 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:09:17,723 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9d50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:09:17,724 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:09:24,737 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9080390>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:09:24,738 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:09:31,749 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908e790>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:09:31,750 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:09:38,761 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908e450>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:09:38,762 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:09:45,775 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab310>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:09:45,776 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:09:52,789 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9065650>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:09:52,789 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:09:59,801 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9070e50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:09:59,802 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:10:06,811 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b8f50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:10:06,812 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:10:13,817 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9066c10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:10:13,817 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:10:20,827 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8e50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:10:20,828 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:10:27,837 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8d50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:10:27,838 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:10:34,849 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908f550>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:10:34,850 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:10:41,863 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a53d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:10:41,863 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:10:48,873 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b7a50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:10:48,874 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:10:55,887 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92ab710>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:10:55,887 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:11:02,899 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a6990>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:11:02,900 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:11:09,910 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908fa50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:11:09,911 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:11:16,920 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908d0d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:11:16,921 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:11:23,933 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8490>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:11:23,933 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:11:30,941 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9064a50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:11:30,941 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:11:37,954 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9070490>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:11:37,954 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:11:44,965 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9096190>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:11:44,965 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:11:51,977 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ba750>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:11:51,978 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:11:58,985 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab010>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:11:58,985 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:12:05,997 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab050>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:12:05,997 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:12:13,009 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908dc50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:12:13,010 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:12:20,020 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a6cd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:12:20,021 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:12:27,034 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b6110>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:12:27,034 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:12:34,049 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9079410>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:12:34,050 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:12:41,058 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a6a90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:12:41,059 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:12:48,072 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908d5d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:12:48,072 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:12:55,081 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908e710>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:12:55,081 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:13:02,089 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8190>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:13:02,089 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:13:09,098 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9064dd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:13:09,099 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:13:16,108 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a2210>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:13:16,109 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:13:23,123 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb907b3d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:13:23,123 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:13:30,134 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa050>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:13:30,135 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:13:37,139 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9b90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:13:37,142 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:13:44,153 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908dc90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:13:44,153 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:13:51,162 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908f310>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:13:51,174 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:13:58,185 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a6e10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:13:58,185 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:14:05,197 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9095510>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:14:05,198 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:14:12,210 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9079390>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:14:12,211 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:14:19,225 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9097550>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:14:19,226 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:14:26,238 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a7d50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:14:26,239 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:14:33,247 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab710>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:14:33,247 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:14:40,257 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aba10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:14:40,258 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:14:47,269 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9090>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:14:47,270 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:14:54,281 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ba490>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:14:54,282 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:15:01,297 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908cd90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:15:01,297 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:15:08,310 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bb110>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:15:08,310 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:15:15,319 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9450>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:15:15,320 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:15:22,334 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90abbd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:15:22,334 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:15:29,347 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa010>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:15:29,347 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:15:36,356 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9095950>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:15:36,357 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:15:43,369 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908e6d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:15:43,370 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:15:50,384 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9071790>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:15:50,385 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:15:57,397 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9096e90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:15:57,398 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:16:04,411 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a6650>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:16:04,412 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:16:11,421 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9e90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:16:11,422 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:16:18,433 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab690>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:16:18,434 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:16:25,445 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bbf10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:16:25,445 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:16:32,457 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9a90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:16:32,458 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:16:39,471 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9080910>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:16:39,472 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:16:46,484 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90baf10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:16:46,485 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:16:53,497 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9850>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:16:53,498 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:17:00,511 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9990>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:17:00,512 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:17:07,524 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90abfd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:17:07,524 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:17:14,533 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90703d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:17:14,533 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:17:21,542 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9096990>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:17:21,543 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:17:28,557 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9080450>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:17:28,558 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:17:35,567 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9095790>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:17:35,568 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:17:42,577 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a53d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:17:42,578 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:17:49,591 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8b10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:17:49,591 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:17:56,604 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908c290>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:17:56,605 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:18:03,618 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b8090>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:18:03,619 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:18:10,631 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9510>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:18:10,631 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:18:17,642 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a91d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:18:17,642 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:18:24,655 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bb350>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:18:24,655 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:18:31,663 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b8390>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:18:31,664 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:18:38,672 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa510>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:18:38,673 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:18:45,681 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a93d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:18:45,682 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:18:52,693 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9083450>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:18:52,693 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:18:59,704 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9097910>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:18:59,705 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:19:06,713 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9065490>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:19:06,714 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:19:13,722 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9096f10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:19:13,723 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:19:20,731 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9080f10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:19:20,732 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:19:27,740 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab810>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:19:27,741 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:19:34,750 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aaa10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:19:34,751 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:19:41,755 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bb0d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:19:41,755 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:19:48,765 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92ab290>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:19:48,765 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:19:55,777 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9064cd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:19:55,777 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:20:02,787 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b8e50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:20:02,787 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:20:09,796 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9071f50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:20:09,797 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:20:16,806 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9990>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:20:16,808 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:20:23,817 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9c90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:20:23,818 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:20:30,831 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a6350>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:20:30,832 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:20:37,845 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9064090>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:20:37,846 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:20:44,861 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a07d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:20:44,862 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:20:51,875 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b6b10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:20:51,875 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:20:58,889 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9081890>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:20:58,889 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:21:05,901 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aaa90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:21:05,902 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:21:12,916 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa210>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:21:12,916 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:21:19,926 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bb0d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:21:19,927 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:21:26,939 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92abb50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:21:26,939 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:21:33,951 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9079910>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:21:33,952 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:21:40,961 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b8e50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:21:40,962 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:21:47,977 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b8090>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:21:47,978 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:21:54,987 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a95d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:21:54,988 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:22:01,997 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa990>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:22:01,997 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:22:09,009 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a7050>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:22:09,010 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:22:16,019 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90960d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:22:16,020 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:22:23,026 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb907ac90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:22:23,026 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:22:30,041 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a6890>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:22:30,041 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:22:37,050 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908f510>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:22:37,050 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:22:44,059 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9c50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:22:44,059 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:22:51,072 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab3d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:22:51,073 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:22:58,086 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bbf90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:22:58,086 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:23:05,097 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9066350>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:23:05,098 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:23:12,106 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90913d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:23:12,106 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:23:19,113 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90baa90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:23:19,113 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:23:26,121 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9071d50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:23:26,121 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:23:33,133 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa1d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:23:33,133 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:23:40,141 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab810>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:23:40,141 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:23:47,145 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a6850>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:23:47,146 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:23:54,156 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90941d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:23:54,157 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:24:01,173 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9093390>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:24:01,173 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:24:08,185 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa9d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:24:08,186 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:24:15,195 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa450>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:24:15,195 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:24:22,205 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb907a890>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:24:22,206 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:24:29,220 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a6890>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:24:29,221 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:24:36,234 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b4410>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:24:36,235 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:24:43,248 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92abc50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:24:43,249 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:24:50,260 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9065c50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:24:50,261 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:24:57,274 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92ab710>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:24:57,275 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:25:04,287 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b7690>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:25:04,287 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:25:11,296 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a85d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:25:11,297 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:25:18,307 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa990>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:25:18,307 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:25:25,318 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9079f10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:25:25,319 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:25:32,329 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9079d10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:25:32,329 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:25:39,343 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9065910>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:25:39,344 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:25:46,354 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb907a590>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:25:46,355 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:25:53,368 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90abc10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:25:53,369 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:26:00,382 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab490>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:26:00,382 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:26:07,396 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a6ad0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:26:07,397 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:26:14,410 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b5250>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:26:14,411 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:26:21,424 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92abcd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:26:21,425 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:26:28,439 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9082e90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:26:28,440 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:26:35,453 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b49d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:26:35,454 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:26:42,467 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b7590>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:26:42,468 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:26:49,478 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9f90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:26:49,479 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:26:56,492 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a91d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:26:56,493 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:27:03,506 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9078590>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:27:03,507 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:27:10,520 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9081c50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:27:10,521 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:27:17,535 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a1290>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:27:17,536 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:27:24,545 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9078f90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:27:24,546 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:27:31,559 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90663d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:27:31,560 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:27:38,572 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa9d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:27:38,573 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:27:45,582 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a4b50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:27:45,582 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:27:52,596 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b7d90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:27:52,596 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:27:59,610 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92aaa50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:27:59,610 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:28:06,625 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9070bd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:28:06,626 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:28:13,639 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9081c50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:28:13,640 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:28:20,653 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b5510>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:28:20,654 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:28:27,667 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa2d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:28:27,668 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:28:34,681 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab710>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:28:34,682 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:28:41,695 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a0f10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:28:41,696 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:28:48,709 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9079310>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:28:48,710 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:28:55,725 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9073050>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:28:55,726 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:29:02,739 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9079f10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:29:02,740 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:29:09,753 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a93d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:29:09,754 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:29:16,767 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9210>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:29:16,768 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:29:23,781 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a6550>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:29:23,782 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:29:30,794 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9080050>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:29:30,795 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:29:37,803 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a9a90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:29:37,804 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:29:44,818 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9095390>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:29:44,819 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:29:51,832 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90814d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:29:51,833 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:29:58,847 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b4650>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:29:58,847 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:30:05,853 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90abdd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:30:05,854 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:30:12,865 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9d10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:30:12,866 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:30:19,875 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9071b10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:30:19,875 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:30:26,885 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9704650>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:30:26,885 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:30:33,900 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908d650>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:30:33,901 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:30:40,915 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fba1a4b90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:30:40,915 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:30:47,929 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90abad0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:30:47,930 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:30:54,943 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa310>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:30:54,944 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:31:01,957 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a6dd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:31:01,958 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:31:08,971 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9083cd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:31:08,972 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:31:15,986 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92ab390>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:31:15,986 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:31:23,001 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9990>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:31:23,002 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:31:30,015 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9080950>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:31:30,016 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:31:37,029 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b42d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:31:37,030 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:31:44,044 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab4d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:31:44,045 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:31:51,057 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aaf10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:31:51,058 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:31:58,071 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fba1a4b90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:31:58,072 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:32:05,086 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb907a310>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:32:05,086 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:32:12,101 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bac90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:32:12,102 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:32:19,116 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908e190>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:32:19,116 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:32:26,130 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9094a10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:32:26,131 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:32:33,141 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab910>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:32:33,141 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:32:40,153 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a65d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:32:40,153 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:32:47,162 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b7490>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:32:47,163 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:32:54,177 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bb110>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:32:54,178 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:33:01,193 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9093150>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:33:01,195 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:33:08,209 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b6890>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:33:08,209 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:33:15,219 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a03d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:33:15,220 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:33:22,233 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa510>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:33:22,234 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:33:29,243 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8890>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:33:29,244 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:33:36,254 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9066150>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:33:36,255 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:33:43,269 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb907af50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:33:43,269 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:33:50,286 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9090d90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:33:50,287 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:33:57,301 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8d10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:33:57,302 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:34:04,315 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90abc50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:34:04,316 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:34:11,329 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a9250>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:34:11,330 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:34:18,344 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90baad0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:34:18,344 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:34:25,358 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b8c90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:34:25,358 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:34:32,372 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9096510>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:34:32,372 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:34:39,383 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9070d10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:34:39,383 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:34:46,397 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ba3d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:34:46,397 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:34:53,411 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bb0d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:34:53,412 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:35:00,425 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b6090>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:35:00,426 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:35:07,439 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8110>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:35:07,440 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:35:14,449 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8850>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:35:14,450 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:35:21,465 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a53d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:35:21,465 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:35:28,480 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9072d10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:35:28,481 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:35:35,490 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8a10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:35:35,491 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:35:42,501 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8750>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:35:42,502 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:35:49,511 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b7890>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:35:49,512 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:35:56,526 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9190>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:35:56,527 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:36:03,540 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bb3d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:36:03,541 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:36:10,554 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9096410>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:36:10,555 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:36:17,570 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a3310>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:36:17,571 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:36:24,584 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9f10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:36:24,585 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:36:31,598 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ba7d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:36:31,599 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:36:38,613 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b6090>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:36:38,613 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:36:45,627 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa790>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:36:45,627 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:36:52,638 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa4d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:36:52,638 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:36:59,649 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9436410>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:36:59,650 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:37:06,663 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908de10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:37:06,664 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:37:13,677 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8490>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:37:13,678 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:37:20,689 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aac90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:37:20,690 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:37:27,701 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b5dd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:37:27,702 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:37:34,716 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bbb50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:37:34,717 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:37:41,730 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bb5d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:37:41,731 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:37:48,740 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9096b10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:37:48,741 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:37:55,756 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb908cc10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:37:55,757 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:38:02,769 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ba6d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:38:02,770 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:38:09,784 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9350>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:38:09,785 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:38:16,798 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b5d10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:38:16,799 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:38:23,812 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aba50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:38:23,813 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:38:30,827 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8b50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:38:30,827 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:38:37,841 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a7d50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:38:37,842 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:38:44,855 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9082310>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:38:44,856 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:38:51,869 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb925b810>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:38:51,870 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:38:58,884 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8fd0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:38:58,884 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:39:05,898 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8c50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:39:05,899 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:39:12,909 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bbd10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:39:12,910 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:39:19,921 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9950>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:39:19,921 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:39:26,930 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90958d0>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:39:26,930 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:39:33,941 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9078e50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:39:33,942 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:39:40,955 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b8310>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:39:40,956 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:39:47,970 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90bb890>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:39:47,971 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:39:54,985 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b5310>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:39:54,985 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:40:01,999 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aa190>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:40:02,000 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:40:09,012 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8d50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:40:09,013 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:40:16,026 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb92a5110>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:40:16,027 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:40:23,042 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9066150>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:40:23,043 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:40:30,056 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9070f50>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:40:30,057 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:40:37,071 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90a8210>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:40:37,071 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:40:44,085 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ab050>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:40:44,086 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:40:51,099 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b8550>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:40:51,100 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:40:58,114 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90ba190>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:40:58,115 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:41:05,128 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9096b10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:41:05,129 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:41:12,140 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb9065e10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:41:12,141 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:41:19,153 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b8210>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:41:19,154 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:41:26,163 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b9c90>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:41:26,164 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:41:33,172 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90b6290>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:41:33,173 - Status check - active: True, should_run: False, app: not running
2025-03-27 16:41:40,185 - Failed to check remote commands: HTTPConnectionPool(host='192.168.4.114', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb90aab10>, 'Connection to 192.168.4.114 timed out. (connect timeout=5)'))
2025-03-27 16:41:40,186 - Status check - active: True, should_run: False, app: not running
