2025-04-08 11:12:35,581 - Cleared log file: /home/pi/smartcart/Pick-and-go-CS/src/app/logs/service.log
2025-04-08 11:12:35,696 - Status check - active: True, should_run: True, app: running
2025-04-08 11:12:37,747 - Status check - active: True, should_run: True, app: running
2025-04-08 11:12:39,799 - Status check - active: True, should_run: True, app: running
2025-04-08 11:12:41,895 - Status check - active: True, should_run: True, app: running
2025-04-08 11:12:43,935 - Status check - active: True, should_run: True, app: running
2025-04-08 11:12:45,982 - Status check - active: True, should_run: True, app: running
2025-04-08 11:12:48,036 - Status check - active: True, should_run: True, app: running
2025-04-08 11:12:50,176 - Status check - active: True, should_run: True, app: running
2025-04-08 11:12:52,469 - Status check - active: True, should_run: True, app: running
2025-04-08 11:12:55,583 - Status check - active: True, should_run: True, app: running
2025-04-08 11:12:57,806 - Status check - active: True, should_run: True, app: running
2025-04-08 11:12:59,977 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:02,647 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:04,708 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:06,853 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:09,151 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:11,272 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:13,408 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:15,661 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:18,351 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:20,857 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:23,037 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:25,864 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:27,993 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:30,086 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:32,463 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:34,767 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:36,848 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:39,107 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:41,185 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:43,330 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:45,657 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:47,789 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:50,060 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:52,371 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:54,853 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:56,961 - Status check - active: True, should_run: True, app: running
2025-04-08 11:13:59,196 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:01,248 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:03,443 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:05,530 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:07,680 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:10,037 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:12,160 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:14,232 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:16,401 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:18,494 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:20,631 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:22,683 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:24,945 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:27,057 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:29,232 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:31,519 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:33,649 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:35,728 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:37,938 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:40,277 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:42,331 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:44,419 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:46,719 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:48,957 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:51,179 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:53,610 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:55,726 - Status check - active: True, should_run: True, app: running
2025-04-08 11:14:58,237 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:00,301 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:02,631 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:04,761 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:06,803 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:08,994 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:11,120 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:13,650 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:15,937 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:18,076 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:21,094 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:23,220 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:25,403 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:27,467 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:29,826 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:31,875 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:34,030 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:36,349 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:38,461 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:40,629 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:42,693 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:44,756 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:46,913 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:49,173 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:51,416 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:53,768 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:55,981 - Status check - active: True, should_run: True, app: running
2025-04-08 11:15:58,146 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:00,360 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:02,415 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:04,483 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:06,567 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:08,861 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:10,962 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:13,082 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:15,173 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:17,265 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:19,314 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:21,379 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:23,620 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:25,785 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:28,202 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:30,341 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:32,503 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:34,592 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:36,757 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:39,356 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:41,507 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:43,910 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:46,046 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:48,095 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:50,159 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:52,191 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:54,255 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:56,332 - Status check - active: True, should_run: True, app: running
2025-04-08 11:16:58,408 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:00,684 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:02,884 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:04,933 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:06,984 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:09,219 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:11,379 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:13,614 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:15,738 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:17,885 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:20,237 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:22,497 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:24,734 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:26,935 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:29,093 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:31,269 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:33,360 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:35,548 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:37,740 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:40,027 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:42,146 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:44,357 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:46,591 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:48,699 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:50,857 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:52,898 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:56,034 - Status check - active: True, should_run: True, app: running
2025-04-08 11:17:58,126 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:00,436 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:02,709 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:05,035 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:07,103 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:09,207 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:11,249 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:13,286 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:15,423 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:17,570 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:20,695 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:22,895 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:25,166 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:27,405 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:29,474 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:31,611 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:33,716 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:35,839 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:37,963 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:39,999 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:42,181 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:44,252 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:46,306 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:48,450 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:50,543 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:52,751 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:54,861 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:56,991 - Status check - active: True, should_run: True, app: running
2025-04-08 11:18:59,462 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:01,701 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:03,811 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:06,088 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:08,456 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:10,524 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:12,600 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:14,693 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:16,922 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:19,118 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:21,349 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:23,657 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:25,744 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:27,957 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:30,030 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:32,089 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:34,662 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:36,787 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:39,120 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:41,402 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:43,633 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:45,703 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:47,756 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:49,974 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:52,038 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:54,153 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:56,384 - Status check - active: True, should_run: True, app: running
2025-04-08 11:19:58,449 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:00,553 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:02,736 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:04,916 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:07,010 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:09,239 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:11,336 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:13,434 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:15,503 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:17,602 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:19,878 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:21,929 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:24,210 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:27,278 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:29,684 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:31,754 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:33,804 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:36,029 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:38,181 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:40,230 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:42,273 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:44,507 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:46,586 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:48,841 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:51,169 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:53,334 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:55,596 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:57,650 - Status check - active: True, should_run: True, app: running
2025-04-08 11:20:59,757 - Status check - active: True, should_run: True, app: running
2025-04-08 11:21:01,974 - Status check - active: True, should_run: True, app: running
2025-04-08 11:21:04,140 - Status check - active: True, should_run: True, app: running
2025-04-08 11:21:06,212 - Status check - active: True, should_run: True, app: running
2025-04-08 11:21:08,291 - Status check - active: True, should_run: True, app: running
2025-04-08 11:21:10,358 - Status check - active: True, should_run: True, app: running
2025-04-08 11:21:12,552 - Status check - active: True, should_run: True, app: running
2025-04-08 11:21:15,017 - Status check - active: True, should_run: True, app: running
2025-04-08 11:21:17,223 - Status check - active: True, should_run: True, app: running
2025-04-08 11:21:19,365 - Status check - active: True, should_run: True, app: running
2025-04-08 11:21:21,570 - Status check - active: True, should_run: True, app: running
2025-04-08 11:21:23,991 - Status check - active: True, should_run: True, app: running
2025-04-08 11:21:26,131 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f99303750>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-08 11:21:26,131 - Status check - active: True, should_run: False, app: running
2025-04-08 11:21:26,132 - Stopping app...
2025-04-08 11:21:26,132 - Last app output before stopping:
2025-04-08 11:21:26,132 - QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-pi'
2025-04-08 11:21:26,133 - 2025-04-08 10:50:10,152 - Starting Kiosk Application
2025-04-08 11:21:26,133 - QWidget::setLayout: Attempting to set QLayout "" on SelectModeFrame "", which already has a layout
2025-04-08 11:21:26,133 - error: XDG_RUNTIME_DIR is invalid or not set in the environment.
2025-04-08 11:21:26,134 - 2025-04-08 10:50:11,491 - Main window displayed
2025-04-08 11:21:26,167 - App stopped successfully
2025-04-08 11:21:26,187 - Failed to update status: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/?is_active=True&app_running=False (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9932ea50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-08 11:21:28,272 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9932d050>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-08 11:21:28,273 - Status check - active: True, should_run: False, app: not running
2025-04-08 11:21:30,337 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f993023d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-08 11:21:30,337 - Status check - active: True, should_run: False, app: not running
2025-04-08 11:21:32,444 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f99303c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-04-08 11:21:32,445 - Status check - active: True, should_run: False, app: not running
2025-04-08 11:21:46,637 - Failed to update status: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/?is_active=True&app_running=False (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdffa850>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-08 11:21:46,647 - Service controller started...
2025-04-08 11:21:46,674 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddb4c50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-08 11:21:46,674 - Status check - active: True, should_run: False, app: not running
2025-04-08 11:21:48,679 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddb70d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-08 11:21:48,679 - Status check - active: True, should_run: False, app: not running
2025-04-08 11:21:50,683 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc1510>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-08 11:21:50,684 - Status check - active: True, should_run: False, app: not running
2025-04-08 11:21:52,693 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddb7650>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-08 11:21:52,694 - Status check - active: True, should_run: False, app: not running
2025-04-08 11:21:54,698 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdff6090>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-08 11:21:54,698 - Status check - active: True, should_run: False, app: not running
2025-04-08 11:21:56,702 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdff9cd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-08 11:21:56,702 - Status check - active: True, should_run: False, app: not running
2025-04-08 11:21:58,710 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc3510>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-08 11:21:58,711 - Status check - active: True, should_run: False, app: not running
2025-04-08 11:22:03,766 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd1450>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 11:22:03,766 - Status check - active: True, should_run: False, app: not running
2025-04-08 11:22:08,822 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd3350>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 11:22:08,823 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:03:58,080 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd36d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:03:58,080 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:04:03,135 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd04d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:04:03,135 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:04:08,192 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdffad90>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:04:08,192 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:04:13,280 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc3ed0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:04:13,280 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:04:18,368 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc2190>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:04:18,369 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:04:23,456 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddb57d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:04:23,457 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:04:28,544 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddd510>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:04:28,545 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:04:33,632 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdff6090>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:04:33,632 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:04:38,720 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc20d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:04:38,721 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:04:43,807 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc1b10>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:04:43,807 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:04:48,863 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddb6710>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:04:48,864 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:04:53,919 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdffb4d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:04:53,919 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:04:58,976 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd1f90>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:04:58,976 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:05:04,064 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddeb50>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:05:04,111 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:05:09,183 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdffb550>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:05:09,191 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:05:14,272 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd3490>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:05:14,272 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:05:19,360 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd0610>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:05:19,360 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:05:24,448 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd2550>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:05:24,448 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:05:29,536 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddb4990>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:05:29,536 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:05:34,624 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc0150>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:05:34,624 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:05:39,712 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdff64d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:05:39,713 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:05:44,800 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddf550>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:05:44,801 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:05:49,888 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc0f50>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:05:49,888 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:05:54,976 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddb5910>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:05:54,977 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:06:00,064 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddb4690>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:06:00,064 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:06:05,152 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd1750>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:06:05,153 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:06:10,240 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd1b10>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:06:10,241 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:06:15,328 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdffb1d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:06:15,328 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:06:20,385 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddced0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:06:20,389 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:06:25,472 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddb7890>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:06:25,477 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:06:30,560 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddb6d10>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:06:30,564 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:06:35,648 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd1a10>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:06:35,652 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:06:40,736 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd1050>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:06:40,740 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:06:45,824 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc2650>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:06:45,824 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:06:50,912 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc3f10>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:06:50,916 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:06:56,001 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddd590>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:06:56,005 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:07:01,088 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc3390>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:07:01,092 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:07:06,175 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc34d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:07:06,177 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:07:11,232 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd1cd0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:07:11,232 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:07:16,288 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd29d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:07:16,292 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:07:21,376 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddb67d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:07:21,380 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:07:26,464 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddec50>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:07:26,464 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:07:31,556 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdde54d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:07:31,562 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:07:36,640 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbee3a7d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:07:36,644 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:07:41,728 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddc850>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:07:41,759 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:07:46,816 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddd690>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:07:46,816 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:07:51,904 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd1850>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:07:51,909 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:07:56,992 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd2390>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:07:56,996 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:08:02,080 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc3f50>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:08:02,084 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:08:07,169 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc1250>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:08:07,174 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:08:12,256 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd1e10>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:08:12,261 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:08:17,344 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd2610>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:08:17,344 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:08:22,432 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdffa350>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:08:22,436 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:08:27,520 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddd790>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:08:27,520 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:08:32,607 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbee2d010>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:08:32,608 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:08:37,664 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc0190>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:08:37,664 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:08:42,753 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddb7450>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:08:42,754 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:08:47,840 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddc090>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:08:47,840 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:08:52,928 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddd390>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:08:52,932 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:08:58,016 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddd9d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:08:58,017 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:09:03,104 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc32d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:09:03,104 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:09:08,192 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd04d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:09:08,193 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:09:13,280 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd0690>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:09:13,285 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:09:18,369 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddb7a50>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:09:18,373 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:09:23,456 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd3350>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:09:23,457 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:09:28,544 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd3290>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:09:28,545 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:09:33,632 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdffb710>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:09:33,632 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:09:38,720 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddd810>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:09:38,724 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:09:43,808 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddf210>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:09:43,808 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:09:48,896 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddb4b90>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:09:48,897 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:09:53,985 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdde7410>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:09:53,986 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:09:59,072 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddf390>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:09:59,073 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:10:04,160 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddef50>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:10:04,161 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:10:09,248 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdffba10>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:10:09,248 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:10:14,336 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddc3650>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:10:14,337 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:10:19,424 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd33d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:10:19,425 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:10:24,512 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd1590>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:10:24,513 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:10:29,601 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddf13d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:10:29,602 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:10:34,688 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd08d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:10:34,689 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:10:39,776 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd3750>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:10:39,776 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:10:44,864 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddb70d0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:10:44,865 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:10:49,952 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddcc90>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:10:49,953 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:10:55,040 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddea10>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:10:55,044 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:11:00,128 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdf7f190>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:11:00,162 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:11:05,249 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddf3390>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:11:05,250 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:11:10,368 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddde450>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:11:10,369 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:11:15,455 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdddd050>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-04-08 14:11:15,455 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:11:22,464 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddb7890>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:11:22,464 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:11:24,471 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdffa2d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-08 14:11:24,472 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:11:31,479 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddd1250>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:11:31,479 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:11:38,488 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf1b90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:11:38,488 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:11:45,498 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf9410>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:11:45,499 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:11:52,512 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddd3e50>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:11:52,512 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:11:59,525 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddd1210>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:11:59,525 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:12:06,532 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdffa990>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:12:06,532 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:12:13,545 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdddda90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:12:13,546 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:12:20,555 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdddf9d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:12:20,555 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:12:27,564 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbe3a91d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:12:27,565 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:12:34,579 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfb3d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:12:34,579 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:12:41,588 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddde250>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:12:41,588 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:12:48,595 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdddd590>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:12:48,596 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:12:55,609 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdddf490>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:12:55,609 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:13:02,623 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbe3d8490>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:13:02,623 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:13:09,635 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddd3810>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:13:09,636 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:13:16,645 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfa550>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:13:16,645 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:13:23,658 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde053d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:13:23,658 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:13:30,667 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddd04d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:13:30,667 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:13:37,680 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdff9ad0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:13:37,681 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:13:44,692 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddc1050>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:13:44,693 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:13:51,706 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdddfc90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:13:51,706 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:13:58,719 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdddf850>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:13:58,720 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:14:05,732 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbecd4950>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:14:05,732 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:14:12,745 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde07390>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:14:12,745 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:14:19,756 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddddc50>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:14:19,757 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:14:26,765 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdddf250>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:14:26,766 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:14:33,780 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdddc110>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:14:33,780 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:14:35,784 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdffa3d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-08 14:14:35,784 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:14:37,787 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddfbf50>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-08 14:14:37,787 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:14:39,790 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbddd3250>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-08 14:14:39,791 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:14:41,799 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbde04a10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2025-04-08 14:14:41,800 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:14:48,809 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdffa250>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:14:48,810 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:14:55,822 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddc33d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:14:55,823 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:15:02,831 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddd3bd0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:15:02,832 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:15:09,843 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdddcb10>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:15:09,844 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:15:16,855 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddde610>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:15:16,856 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:15:23,863 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfa550>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:15:23,864 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:15:30,877 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde06350>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:15:30,877 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:15:37,883 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdffa310>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:15:37,883 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:15:44,891 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfa950>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:15:44,892 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:15:51,899 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf9450>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:15:51,899 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:15:58,916 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf3d90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:15:58,916 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:16:05,929 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf11d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:16:05,930 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:16:12,940 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdde65d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:16:12,940 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:16:19,949 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdddfd90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:16:19,949 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:16:26,959 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdde5f90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:16:30,005 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:16:37,015 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf2350>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:16:37,016 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:16:44,024 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf3010>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:16:44,025 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:16:51,033 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf8b90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:16:51,033 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:16:58,042 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf8410>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:16:58,042 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:17:05,055 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbee2d010>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:17:05,055 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:17:12,064 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdddefd0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:17:12,065 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:17:19,073 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdffaf90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:17:19,074 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:17:26,086 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfb4d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:17:26,087 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:17:33,096 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf8c10>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:17:33,097 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:17:40,106 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf2e50>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:17:40,106 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:17:47,111 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf2110>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:17:47,111 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:17:54,120 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdddf0d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:17:54,121 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:18:01,131 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddb59d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:18:01,132 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:18:08,141 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf2090>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:18:08,142 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:18:15,155 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf3350>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:18:15,156 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:18:22,165 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf0550>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:18:22,165 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:18:29,174 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf8d90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:18:29,174 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:18:36,183 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfb750>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:18:36,184 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:18:43,193 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddde890>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:18:43,194 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:18:50,207 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddb4050>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:18:50,207 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:18:57,218 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdffaa10>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:18:57,219 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:19:04,228 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfa850>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:19:04,228 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:19:11,237 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf9bd0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:19:11,237 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:19:18,244 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf3790>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:19:18,245 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:19:25,253 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf2110>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:19:25,254 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:19:32,263 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdde6410>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:19:32,263 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:19:39,273 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddc20d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:19:39,274 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:19:46,284 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf07d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:19:46,284 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:19:53,294 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf3610>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:19:53,295 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:20:00,304 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf3810>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:20:00,304 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:20:07,316 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf9e50>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:20:07,317 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:20:14,327 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdff9ed0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:20:14,327 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:20:21,336 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdddf050>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:20:21,337 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:20:28,351 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddc1f50>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:20:28,351 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:20:35,360 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdffb650>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:20:35,360 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:20:42,373 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf8090>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:20:42,374 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:20:49,387 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfb310>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:20:49,388 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:20:56,401 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf19d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:20:56,401 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:21:03,411 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf0d10>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:21:03,412 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:21:10,424 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdde7090>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:21:10,424 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:21:17,433 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddd25d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:21:17,434 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:21:24,443 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf1e10>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:21:24,443 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:21:31,453 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf2350>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:21:31,453 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:21:38,462 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf81d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:21:38,462 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:21:45,471 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfa410>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:21:45,472 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:21:52,484 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdff9c10>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:21:52,484 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:21:59,492 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdddf050>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:21:59,493 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:22:06,507 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddd1ed0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:22:06,507 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:22:13,519 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdffb1d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:22:13,520 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:22:20,531 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfba50>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:22:20,531 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:22:27,544 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfb410>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:22:27,545 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:22:34,558 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf00d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:22:34,559 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:22:41,568 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf2cd0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:22:41,568 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:22:48,576 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdde6110>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:22:48,576 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:22:55,589 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde04390>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:22:55,590 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:23:02,599 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf1d50>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:23:02,600 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:23:09,608 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf3e50>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:23:09,609 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:23:16,622 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf9510>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:23:16,622 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:23:23,631 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf9f50>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:23:23,632 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:23:30,644 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdffa7d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:23:30,644 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:23:37,657 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdddd4d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:23:37,658 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:23:44,673 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde09390>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:23:44,673 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:23:51,683 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdff9090>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:23:51,684 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:23:58,697 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfa250>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:23:58,697 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:24:05,706 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf8b90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:24:05,706 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:24:12,718 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf10d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:24:12,719 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:24:19,723 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf1f10>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:24:19,723 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:24:26,732 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdde5c90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:24:26,732 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:24:33,744 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde0b2d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:24:33,744 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:24:40,753 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf0650>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:24:40,754 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:24:47,763 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf0fd0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:24:47,764 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:24:54,771 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfbe90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:24:54,772 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:25:01,782 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfbb50>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:25:01,783 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:25:08,791 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdffa8d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:25:08,791 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:25:15,801 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde090d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:25:15,801 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:25:22,811 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde112d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:25:22,811 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:25:29,818 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfa3d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:25:29,818 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:25:36,826 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfa810>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:25:36,827 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:25:43,831 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde0b450>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:25:43,831 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:25:50,835 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde08b90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:25:50,835 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:25:57,844 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde06fd0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:25:57,844 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:26:04,852 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddd1e10>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:26:04,853 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:26:11,865 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddd1a10>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:26:11,865 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:26:18,875 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde04f90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:26:18,875 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:26:25,887 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfbd50>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:26:25,887 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:26:32,895 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf9a10>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:26:32,896 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:26:39,903 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde09c50>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:26:39,903 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:26:46,912 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde0a590>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:26:46,912 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:26:53,920 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddd2bd0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:26:53,921 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:27:00,930 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbe3d8490>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:27:00,930 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:27:07,939 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde0b790>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:27:07,940 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:27:14,954 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde08910>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:27:14,955 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:27:21,968 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfb410>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:27:21,968 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:27:28,982 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf8f90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:27:28,982 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:27:35,995 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddd0110>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:27:35,996 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:27:43,005 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde06910>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:27:43,005 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:27:50,018 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddb73d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:27:50,018 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:27:57,031 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde04890>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:27:57,031 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:28:04,044 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfa650>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:28:04,044 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:28:11,049 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfaa50>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:28:11,050 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:28:18,058 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddd1dd0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:28:18,059 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:28:25,067 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde0ad10>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:28:25,067 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:28:32,080 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde0a290>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:28:32,081 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:28:39,096 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddb71d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:28:39,096 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:28:46,114 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde0b350>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:28:46,115 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:28:53,124 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde0a2d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:28:53,125 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:29:00,134 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde0af90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:29:00,135 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:29:07,143 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfa450>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:29:07,144 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:29:14,155 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddb7790>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:29:14,156 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:29:21,168 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde06e90>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:29:21,168 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:29:28,179 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddc1f50>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:29:28,180 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:29:35,194 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde05c50>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:29:35,195 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:29:42,201 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf9290>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:29:42,201 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:29:49,211 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf9f10>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:29:49,212 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:29:56,225 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde0b410>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:29:56,226 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:30:03,239 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde09810>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:30:03,240 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:30:10,253 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdff6110>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:30:10,254 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:30:17,265 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddc31d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:30:17,265 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:30:24,275 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddd2c10>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:30:24,276 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:30:31,285 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde0a4d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:30:31,285 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:30:38,299 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde0b250>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:30:38,300 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:30:45,313 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf9450>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:30:45,314 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:30:52,327 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddf9ed0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:30:52,328 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:30:59,341 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbde044d0>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:30:59,342 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:31:06,357 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbdddd510>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:31:06,357 - Status check - active: True, should_run: False, app: not running
2025-04-08 14:31:13,371 - Failed to check remote commands: HTTPConnectionPool(host='192.168.5.6', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fbddfb450>, 'Connection to 192.168.5.6 timed out. (connect timeout=5)'))
2025-04-08 14:31:13,372 - Status check - active: True, should_run: False, app: not running
