2025-05-24 16:21:21,436 - Cleared log file: /home/mtech/Workspace/Pick-and-go-CS/src/app/logs/service.log
2025-05-24 16:21:26,445 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94760>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:21:26,446 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:21:33,461 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94f40>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:21:33,463 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:21:40,477 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94bb0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:21:40,477 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:21:47,485 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d949d0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:21:47,486 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:21:54,497 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d70be0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:21:54,497 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:22:01,508 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0bb50>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:22:01,509 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:22:08,521 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b460>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:22:08,522 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:22:15,533 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc4c0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:22:15,533 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:22:22,544 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc9d0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:22:22,545 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:22:29,558 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfca00>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:22:29,558 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:22:36,576 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc610>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:22:36,577 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:22:43,592 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b610>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:22:43,592 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:22:50,604 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0be20>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:22:50,605 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:22:57,622 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d70c40>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:22:57,623 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:23:04,640 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94ac0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:23:04,641 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:23:11,659 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94be0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:23:11,660 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:23:18,680 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94df0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:23:18,680 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:23:25,697 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d941c0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:23:25,697 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:23:32,708 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d704c0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:23:32,709 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:23:39,721 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0bb20>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:23:39,722 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:23:46,735 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0ba90>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:23:46,735 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:23:53,747 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfcac0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:23:53,748 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:24:00,766 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfcdc0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:24:00,766 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:24:07,781 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfcf40>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:24:07,782 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:24:14,793 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfcb50>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:24:14,794 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:24:21,806 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0bac0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:24:21,806 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:24:28,819 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0bbb0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:24:28,819 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:24:35,836 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d70040>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:24:35,837 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:24:42,853 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94370>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:24:42,854 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:24:49,871 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94e20>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:24:49,871 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:24:56,884 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d945e0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:24:56,885 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:25:03,901 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94cd0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:25:03,901 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:25:10,909 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d70d00>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:25:10,909 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:25:17,922 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b100>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:25:17,923 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:25:24,937 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b160>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:25:24,937 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:25:31,949 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfccd0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:25:31,950 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:25:38,962 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfce20>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:25:38,963 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:25:45,976 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc0d0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:25:45,976 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:25:52,990 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfce50>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:25:52,991 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:26:00,003 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0baf0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:26:00,004 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:26:07,019 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0bd60>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:26:07,020 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:26:14,031 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d70280>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:26:14,031 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:26:21,048 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94730>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:26:21,048 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:26:28,060 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d948e0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:26:28,061 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:26:35,073 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94340>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:26:35,074 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:26:42,085 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94fa0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:26:42,085 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:26:49,097 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d70490>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:26:49,097 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:26:56,114 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b040>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:26:56,115 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:27:03,132 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b700>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:27:03,133 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:27:10,151 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc460>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:27:10,152 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:27:17,169 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfcf40>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:27:17,170 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:27:24,189 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc760>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:27:24,189 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:27:31,201 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc130>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:27:31,201 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:27:38,218 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b1c0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:27:38,219 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:27:45,236 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b4c0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:27:45,237 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:27:52,251 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d701c0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:27:52,252 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:27:59,261 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94310>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:27:59,262 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:28:06,274 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94ee0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:28:06,275 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:28:13,294 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94f40>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:28:13,294 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:28:20,312 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94400>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:28:20,313 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:28:27,324 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d704f0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:28:27,325 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:28:34,333 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0bdf0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:28:34,334 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:28:41,345 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0bdc0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:28:41,346 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:28:48,358 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc5e0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:28:48,358 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:28:55,369 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc7f0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:28:55,370 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:29:02,382 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc9d0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:29:02,382 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:29:09,397 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc910>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:29:09,397 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:29:16,414 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b850>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:29:16,414 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:29:23,426 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b520>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:29:23,427 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:29:30,444 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d70e50>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:29:30,444 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:29:37,453 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94f10>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:29:37,453 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:29:44,469 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94af0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:29:44,470 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:29:51,483 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94d90>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:29:51,483 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:29:58,498 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d947f0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:29:58,498 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:30:05,513 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d705b0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:30:05,514 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:30:12,528 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0bdf0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:30:12,529 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:30:19,546 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b0a0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:30:19,546 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:30:26,557 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc190>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:30:26,558 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:30:33,570 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfccd0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:30:33,571 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:30:40,583 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc250>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:30:40,583 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:30:47,595 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc100>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:30:47,595 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:30:54,605 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b760>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:30:54,606 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:31:01,618 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b640>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:31:01,618 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:31:08,631 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d70280>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:31:08,631 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:31:15,643 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d946d0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:31:15,643 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:31:22,655 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d941c0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:31:22,655 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:31:29,666 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94b20>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:31:29,667 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:31:36,684 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94700>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:31:36,684 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:31:43,698 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d704c0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:31:43,698 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:31:50,716 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0bdf0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:31:50,717 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:31:57,731 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b340>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:31:57,732 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:32:04,743 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc520>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:32:04,743 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:32:11,755 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfcb20>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:32:11,755 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:32:18,767 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfcbb0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:32:18,768 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:32:25,778 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfcfa0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:32:25,779 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:32:32,793 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0bfd0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:32:32,793 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:32:39,805 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b940>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:32:39,805 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:32:46,818 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d702b0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:32:46,818 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:32:53,830 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94ac0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:32:53,830 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:33:00,842 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94e20>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:33:00,843 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:33:07,855 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94850>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:33:07,856 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:33:14,873 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d943d0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:33:14,874 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:33:21,885 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d70220>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:33:21,886 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:33:23,890 - Cleared log file: /home/mtech/Workspace/Pick-and-go-CS/src/app/logs/app.log
2025-05-24 16:33:28,899 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0bdf0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:33:28,899 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:33:35,911 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b7f0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:33:35,911 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:33:42,927 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc700>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:33:42,928 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:33:49,938 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc280>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:33:49,939 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:33:56,958 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc730>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:33:56,958 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:34:03,969 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc040>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:34:03,970 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:34:10,986 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0bf10>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:34:10,986 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:34:17,998 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b9a0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:34:17,999 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:34:25,016 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d70d60>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:34:25,016 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:34:32,032 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94670>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:34:32,033 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:34:39,049 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94f70>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:34:39,050 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:34:46,069 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94610>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:34:46,069 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:34:53,081 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d944c0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:34:53,081 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:35:00,090 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d70bb0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:35:00,090 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:35:07,102 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0bdf0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:35:07,103 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:35:14,120 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b580>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:35:14,120 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:35:21,129 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc790>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:35:21,130 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:35:28,141 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc250>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:35:28,142 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:35:35,154 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc220>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:35:35,155 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:35:42,165 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92cfc370>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:35:42,165 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:35:49,173 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b8b0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:35:49,174 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:35:56,185 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d0b5b0>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:35:56,185 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:36:03,198 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d70040>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:36:03,199 - Status check - active: True, should_run: False, app: not running
2025-05-24 16:36:10,215 - Failed to check remote commands: HTTPConnectionPool(host='172.26.31.232', port=9000): Max retries exceeded with url: /api/devices/raspi_cart_001/status/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f92d94460>, 'Connection to 172.26.31.232 timed out. (connect timeout=5)'))
2025-05-24 16:36:10,215 - Status check - active: True, should_run: False, app: not running
